server:
  port: 8084
dubbo:
  application:
    name: shop_sso
  registry:
    address: zookeeper://192.168.25.128:2181
  consumer:
    check: false
    timeout: 2000
spring:
  redis:
    host: 192.168.25.128